# Site settings
author: Ronny Toribio
title: 
header-img: img/home-bg.png
email: ronnytoribio1@hotmail.com
copyright_name: Ronny Toribio
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: rtblacko
github_username:  RTBlanco

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
